### ISSUE TITLE
Error message when using golang build

### ISSUE THREAD

**Issue by zenpoet** [streamingfast/solana-go#14]
Followed directions on github.

Get following error/warning:

go get -u -v github.com/streamingfast/solana-go/cmd/slnc
go: downloading github.com/streamingfast/solana-go v0.2.0
go get: github.com/streamingfast/solana-go@v0.2.0: parsing go.mod:
	module declares its path as: github.com/dfuse-io/solana-go
	        but was required as: github.com/streamingfast/solana-go

Looks like some path weren't updated?

**Comment by maoueh** [comment]
All fixed in latest released version.
