### ISSUE TITLE
How to place an order in the order book

### ISSUE THREAD

**Issue by trading-peter** [streamingfast/solana-go#4]
I hope I don't get totally wrong what this library aims for. I'm basically thinking it aims to be the go version of that web3 lib?
I was wondering how I would set orders? Is that implemented?

**Comment by maoueh** [comment]
Sorry long delay, no it's not implemented, well more or less. This library could be used to craft the correct instructions and generate a transaction that could then be sent to the network for consumption. I think all the building blocks are in there now to do what you want, closing.

Feel free to re-open if you need further help.
